### PR TITLE
Moved back button outside FormContentContainer

### PR DESCRIPTION
**Pull request by al-chang**
## Why

https://app.clickup.com/t/1tmncmr

Move the back button above the form title to make it consistent with the appearance on other pages. 

## This PR

Moved the BackButton component out of the container. 

Some checks were failing following the merge of the react query refactor. I've updated the data visualization container to use react query to fix these issues. 

## Screenshots

 

Screen Shot 2021-12-08 at 10 27 10 PM
Screen Shot 2021-12-14 at 6 22 41 PM

## Verification Steps

 

Select the Form History button on the home page. Notice how the back button is above the title. 
Repeat above steps for the Fill Out A Form button.

### CODE REVIEW

**Review by maxsebso — DISMISSED** [review]
LGTM

**Review by rymaju — APPROVED** [review]
LGTM 💯

**Review by rymaju — APPROVED** [review]
Slightly confused why the diff is so large but I'm assuming thats either my fault or git's fault/

**Comment by maxsebso** [comment]
outdated

**Pull request closed without merging**
