### PR TITLE
changed columns to display names instead of titles

### PR DESCRIPTION
**Pull request by DerekL27**
## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/866744728/pulses/1500401148)

Changes user ID and school ID to their corresponding names

Can't verify if this works because the tab to view submitted reports is giving me an error

### CODE REVIEW

**Comment by justinkonecny** [comment]
@DerekL27 can you address the build errors?

**Comment by granttebeau** [comment]
At the current moment this change won't work as it's supposed to- the past submission reports doesn't have a "userName" or "schoolName" field (see https://docs.c4cneu.com/hats/api-spec-school-report/#get-paginated-reports-for-one-school). 

Since this page is displaying the reports of a single school, we can probably pass the school name through props or grab it from the redux state and just display that for each form

However, for the user name, we'll have to map through each of the reports from the state and make an api call to get that user's name (could just do this using an async function and a for loop) OR we can just add the user name to the response for that endpoint (which would probably be way easier in the long run). Thoughts @justinkonecny ?

**Comment by granttebeau** [comment]
any updates on this^ ?

**Comment by maxsebso** [comment]
> any updates on this^ ?

^^

**Comment by granttebeau** [comment]
@DerekL27 what's up with the status of this ticket

**Comment by DerekL27** [comment]
> @DerekL27 what's up with the status of this ticket

so sorry just saw this. It should be good I just forgot to change the devdocs for paginated reports. I changed reportGeneric and getPaginatedReports is just a list of that so it should be fine

**Comment by DerekL27** [comment]
> > @DerekL27 what's up with the status of this ticket
> 
> so sorry just saw this. It should be good I just forgot to change the devdocs for paginated reports. I changed reportGeneric and getPaginatedReports is just a list of that so it should be fine

@rymaju and I tested it and it works as far as I know

**Review by maxsebso — APPROVED** [review]
LGTM

**Pull request merged**
